[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --prefix backend"]

[phases.build]
cmds = ["npm run build --prefix backend"]

[start]
cmd = "cd backend && node dist/scripts/initDb.js && npm start"
