[phases.setup]
nixPkgs = ["nodejs_20", "python3", "gcc", "gnumake"]

[phases.install]
cmds = ["npm install --prefix kulinermedanfood-main/backend"]

[phases.build]
cmds = ["npm run build --prefix kulinermedanfood-main/backend"]

[start]
cmd = "cd kulinermedanfood-main/backend && node dist/scripts/initDb.js && npm start"
