services:
  - type: web
    name: bhinneka-rasa-backend
    runtime: node
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: .database/foodmap.db
      - key: JWT_SECRET
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
